version: '3.8'

services:
  backend:
    build: .
    container_name: sentry_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    # LOAD VARIABLES FROM .env FILE
    env_file:
      - .env
    depends_on:
      - chromadb_server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  chromadb_server:
    image: chromadb/chroma:latest
    container_name: sentry_chromadb
    ports:
      - "8001:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE